### ISSUE TITLE
Gallery Redesign

### ISSUE THREAD

**Issue by zakuArbor** [cumathsoc/cumathsoc.github.io#39]
* Collage
* Hover to get description (change opacity of image and reveal text
* gallery becomes homepage
* welcoming event: crop image
* resize all images
* https://www.w3schools.com/howto/howto_js_image_grid.asp

**Comment by zakuArbor** [comment]
**file:** `gallery.html`

**Tasks:**
- [ ] upload images from Drive `2023-2024/Gallery/Combintorial Game Night/Official/cropped/` to github under `images/events/cgt/`
- [ ] display images on `gallery.html`
- [ ] display vertical images side by side
